version: '3'

networks:
  lumen:

services:
  
  redis:
    image: redis:alpine
    container_name: spp-redis 
  
  postgres:
    image: postgres:latest
    container_name: spp-postgresql
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=spp
    ports:
      - "5432:5432"
    networks:
      - lumen

  nginx:
    image: nginx:stable-alpine
    container_name: spp-webserver
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - lumen

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spp-php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - lumen
  
  composer:
    image: composer:latest
    container_name: spp-composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - lumen


  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - lumen

volumes:
  postgres: {}